Repository BedalFriend/BaedalFriend-BE, pull requests merged in 2022-12, with the labels that each got.

#67 Hotfix Change message
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
Labels: bug

#69 Fix: 채팅방종료Api 수정
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ParticipantNumber.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
  src/main/java/com/hanghae/baedalfriend/repository/ParticipantRepository.java
Labels: enhancement

#70 Hotfix Change ParticipantNumber
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoomMember.java
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
Labels: bug

#72 Hotfix 키워드 null 일때 전체 카테고리
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
Labels: bug

#73 Change: s3관련 주석 풀음
  src/main/java/com/hanghae/baedalfriend/configuration/S3Config.java
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: enhancement

#74 Fix:login&reissue시 해당 유저가 진행중인 게시글에 참여하고 있는지 확인하는 로직 변경
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
Labels: enhancement

#75 Feat: Add 마이페이지 이미지 업로드
  src/main/java/com/hanghae/baedalfriend/Mypage/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/request/MypageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/response/MypageImgResponseDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: enhancement

#77 Add content column in post table
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/PostRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/GetAllPostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostDetailResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: enhancement

#79 메인 제목검색에서 공백으로 검색 시 검색되는 이슈 수정
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
Labels: bug

#81 카카오 로그인한 사용자의 닉네임이 프로필 화면에 잘못 노출되는 현상 수정
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
Labels: bug

#84 [이슈] 검색 코드 수정
  src/main/java/com/hanghae/baedalfriend/controller/SearchController.java
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
Labels: bug

#86 Add: 해당 유저가 진행중인 게시글에 참여하고 있는지 확인하는 로직
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
Labels: bug

#87 Feature/mypage 주소 API 추가했습니다
  src/main/java/com/hanghae/baedalfriend/Mypage/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/request/MypageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: enhancement

#88 Hotfix mypage code change
  src/main/java/com/hanghae/baedalfriend/Mypage/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
Labels: bug

#92 Add: 프로필 수정 로직 다시 작성
  src/main/java/com/hanghae/baedalfriend/Mypage/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/request/MypageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
Labels: bug, enhancement

#95 Fix: Clear 닉네임 조건받는 것 삭제
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
Labels: bug

#96 Hotfix:채팅메시지시간수정
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChattingController.java
Labels: bug

#97 Change: message type 이름변경
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatMessage.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatService.java
Labels: enhancement

#98 Fix: 회원 수정 완료
  src/main/java/com/hanghae/baedalfriend/Mypage/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/Mypage/service/MypageService.java
Labels: bug

#107 Feature/mypage
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/request/PasswordDeleteRequestDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/request/PasswordRequestDto.java
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/response/MypageImgResponseDto.java
  src/main/java/com/hanghae/baedalfriend/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/MypageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/MypageHistoryResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/MypageResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/MypageService.java
Labels: enhancement

#108 Fix: 불필요한 파일을 삭제 후 관련 코드를 삭제
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: bug

#109 Fix: event 관련 주석 풀었습니다
  src/main/java/com/hanghae/baedalfriend/controller/EventController.java
  src/main/java/com/hanghae/baedalfriend/domain/Event.java
  src/main/java/com/hanghae/baedalfriend/service/EventService.java
Labels: enhancement

#110 Fix: soft delete 기능을 뺐습니다
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/service/MypageService.java
Labels: bug

#111 Fix: 마이페이지 내가 쓴 게시글 수정
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/service/MypageService.java
Labels: bug

#112 Fix: 마이페이지 내가 쓴 게시글 형식 수정
  src/main/java/com/hanghae/baedalfriend/controller/MypageController.java
  src/main/java/com/hanghae/baedalfriend/service/MypageService.java
Labels: bug

#114 Hotfix kakaoLogin emailId issue update
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/KakaoMemberInfoDto.java
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
Labels: bug

#117 Fix: scheduler
  src/main/java/com/hanghae/baedalfriend/shared/scheduler/DeleteScheduler.java
  src/main/java/com/hanghae/baedalfriend/shared/scheduler/DeleteService.java
Labels: bug

#118 [기능추가] 인기검색 기능 추가
  src/main/java/com/hanghae/baedalfriend/controller/SearchController.java
  src/main/java/com/hanghae/baedalfriend/repository/PopularSearchWordRepository.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/repository/RecentSearchTermsRepository.java
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
Labels: enhancement

#119 fix: 인자보다 미래일 때 true가 리턴
  src/main/java/com/hanghae/baedalfriend/shared/scheduler/DeleteScheduler.java
Labels: bug

#123 Hotfix: 채널공구종료로직수정
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChattingController.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoomMember.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatService.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
Labels: bug

#124 [기능추가] Review
  src/main/java/com/hanghae/baedalfriend/controller/ReviewController.java
  src/main/java/com/hanghae/baedalfriend/domain/Review.java
  src/main/java/com/hanghae/baedalfriend/domain/converter/ReviewCategory.java
  src/main/java/com/hanghae/baedalfriend/domain/converter/ReviewCategoryConverter.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/ReviewRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/ReviewResponseDto.java
  src/main/java/com/hanghae/baedalfriend/repository/ReviewRepository.java
  src/main/java/com/hanghae/baedalfriend/service/ReviewService.java
Labels: enhancement

#125 [기능추가] 리뷰창view Api 추가
  build.gradle
  src/main/java/com/hanghae/baedalfriend/controller/ReviewController.java
  src/main/java/com/hanghae/baedalfriend/domain/converter/ReviewCategory.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/ReviewResponseDto.java
  src/main/java/com/hanghae/baedalfriend/repository/ReviewRepository.java
  src/main/java/com/hanghae/baedalfriend/service/ReviewService.java
Labels: enhancement

#127 Fix: 이미지 프로필 변경시 이름이 길 경우 잘못된 형식입니다라는 에러가 뜨는 오류
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: bug

#129 Fix: isClosed의 결과값이 반영이 되지 않은 이슈 수정
  src/main/java/com/hanghae/baedalfriend/service/MypageService.java
Labels: bug

#130 최근검색어 중복 제거 추가
  src/main/java/com/hanghae/baedalfriend/controller/SearchController.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/PostRequestDto.java
  src/main/java/com/hanghae/baedalfriend/repository/KeywordRepository.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepositoryCustom.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepositoryImpl.java
  src/main/java/com/hanghae/baedalfriend/service/KeywordService.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: bug

#131 Refactor : query dsl
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/request/ChatRoomRequestDto.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
Labels: enhancement

#133 Feature/scheduler
  src/main/java/com/hanghae/baedalfriend/shared/scheduler/DeleteScheduler.java
Labels: enhancement

#138 여러분 죄송합니다 ㅠㅠ
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
Labels: bug
