Repository BedalFriend/BaedalFriend-BE, pull requests merged in 2022-11, with the labels that each got.

#22 Feat: 채팅방Api구현
  src/main/java/com/hanghae/baedalfriend/chat/configuration/WebSockConfig.java
  src/main/java/com/hanghae/baedalfriend/chat/configuration/handler/StompHandler.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChattingController.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/response/ChatMessageResponseDto.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatMessage.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatMessageRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/RoomRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatService.java
  src/main/java/com/hanghae/baedalfriend/controller/PostController.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: enhancement

#24 Fix Change feature/login add address
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/MemberRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/MemberResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
Labels: enhancement

#25 Fix: 채팅방입장Api 추가, 필요없는 jpa 삭제
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomJpaRepository.java
Labels: bug

#29 Feature/s3
  build.gradle
  src/main/java/com/hanghae/baedalfriend/configuration/S3Config.java
  src/main/java/com/hanghae/baedalfriend/dto/PhotoDto.java
  src/main/java/com/hanghae/baedalfriend/service/S3Service.java
Labels: enhancement

#30 Fix: Change Event, Add s3feature
  src/main/java/com/hanghae/baedalfriend/controller/EventController.java
  src/main/java/com/hanghae/baedalfriend/domain/Event.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/EventResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/EventService.java
Labels: enhancement

#31 Fix: Change EventUpRequestDto
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/EventUpRequestDto.java
Labels: enhancement

#33 Fix : 소켓통신할 때는 httprequest 안되는 오류
  src/main/java/com/hanghae/baedalfriend/chat/configuration/handler/StompHandler.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChattingController.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatMessage.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatMessageRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatService.java
  src/main/java/com/hanghae/baedalfriend/shared/ChatRoomException.java
Labels: bug

#34 Fix:채팅룸관련 Api test까지 완료
  build.gradle
  src/main/java/com/hanghae/baedalfriend/chat/configuration/handler/StompHandler.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChattingController.java
  src/main/java/com/hanghae/baedalfriend/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatMessage.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatMessageJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatMessageRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatService.java
  src/main/java/com/hanghae/baedalfriend/domain/Timestamped.java
  src/main/resources/application-alpha.properties
Labels: enhancement

#40 Add : 게시글들 get해올때 해당 게시글에 참여중인 유저목록도 포함
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/GetAllPostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: enhancement

#41 Add : response 값 추가
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/domain/Member.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/MemberResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostDetailResponseDto.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: enhancement

#45 participantNumber response값 수정
  README.md
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: enhancement

#47 Feat : 방장일 때 퇴장Api추가
  src/main/java/com/hanghae/baedalfriend/chat/controller/ChatRoomController.java
  src/main/java/com/hanghae/baedalfriend/chat/repository/ChatRoomMemberJpaRepository.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
Labels: enhancement

#49 Fix EmailAuth
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/MemberResponseDto.java
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: bug

#50 Fix : 로그인,reissue response값 수정
  src/main/java/com/hanghae/baedalfriend/service/MemberService.java
Labels: enhancement

#53 Hotfix kakaoLogin
  src/main/java/com/hanghae/baedalfriend/service/KakaoMemberService.java
Labels: enhancement

#56 Hotfix_Search
  src/main/java/com/hanghae/baedalfriend/configuration/CorsConfiguration.java
  src/main/java/com/hanghae/baedalfriend/controller/PostController.java
  src/main/java/com/hanghae/baedalfriend/controller/SearchController.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
  src/main/java/com/hanghae/baedalfriend/domain/Timestamped.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/PostRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/GetAllPostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostDetailResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/repository/PostRepository.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
Labels: bug

#58 Fix : 게시글삭제 오류
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: bug

#59 Fix : 채팅방입장오류
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: bug

#60 Hotfix sortBy participantNumber
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoom.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ChatRoomMember.java
  src/main/java/com/hanghae/baedalfriend/chat/entity/ParticipantNumber.java
  src/main/java/com/hanghae/baedalfriend/chat/service/ChatRoomService.java
  src/main/java/com/hanghae/baedalfriend/controller/PostController.java
  src/main/java/com/hanghae/baedalfriend/controller/SearchController.java
  src/main/java/com/hanghae/baedalfriend/domain/Post.java
  src/main/java/com/hanghae/baedalfriend/dto/requestdto/PostRequestDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/CategoryResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/GetAllPostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/dto/responsedto/PostResponseDto.java
  src/main/java/com/hanghae/baedalfriend/repository/ParticipantRepository.java
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
  src/main/java/com/hanghae/baedalfriend/service/SearchService.java
  src/main/java/com/hanghae/baedalfriend/shared/Participant.java
Labels: bug, enhancement

#64 Hotfix_participantNumber Delete member check logic in participantNumber url
  src/main/java/com/hanghae/baedalfriend/service/PostService.java
Labels: bug, enhancement

#66 Fix: 오타 수정했습니다
  src/main/java/com/hanghae/baedalfriend/Mypage/dto/response/MypageResponseDto.java
Labels: bug
